# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d470a0a05add27a6c2a2d9d9c88f33be1019f72939c482c0cab129bb183ebe650760a29778b3031297bc76a0ba5ca4e24586bb938649ac2eca4b7bacd79f0d55

test:
  secret_key_base: 53794c3026589310e62bc79bacb85283a179d880d6b42bb5e145aa2ecc5fa3d4dfe2bd92b48f3dc5c43f94a207b1e40a86eebe5fe9813ddc51fb88a2a3468e8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
